export const CONFIG_UPDATE = 'CONFIG_UPDATE';
export const MASTER_STATUS_UPDATE = 'MASTER_STATUS_UPDATE';
export const SLAVES_UPDATE = 'SLAVES_UPDATE';
export const DIALOG_OPEN = 'DIALOG_OPEN';
export const DIALOG_CLOSE = 'DIALOG_CLOSE';
