export const LOADER_SHOW = 'LOADER_SHOW';
export const LOADER_HIDE = 'LOADER_HIDE';
export const TOAST_SHOW = 'TOAST_SHOW';
export const TOAST_HIDE = 'TOAST_HIDE';
export const MENU_SHOW = 'MENU_SHOW';
export const MENU_HIDE = 'MENU_HIDE';
export const ACCOUNT_LOGIN = 'ACCOUNT_LOGIN';
export const ACCOUNT_LOGOUT = 'ACCOUNT_LOGOUT';
export const ACCOUNT_REGISTER = 'ACCOUNT_REGISTER'; // no reducer
export const ACCOUNT_UPDATE = 'ACCOUNT_UPDATE';
export const ACCOUNTS_UPDATE = 'ACCOUNTS_UPDATE';
export const AGEGROUPS_UPDATE = 'AGEGROUPS_UPDATE';
export const LEAGUES_UPDATE = 'LEAGUES_UPDATE';
export const TEAMS_UPDATE = 'TEAMS_UPDATE';
